### PR TITLE
Implements Filter

### PR DESCRIPTION
**Pull request by ghost**
This **PR** address **Issue** #10.

**Steps to filter Table**:

1. Select the appropriate filters, 
for example "_working_", "_not fixed_" to show the table rows having those values.
2. Click on the **Filter** _button_ below the filters list.
3. Table is seen as shown in the following figure. 

**Output**:

filter

### CODE REVIEW

**Review by nguyenLisa — CHANGES_REQUESTED** [review]
Hi @gsvarma , the code does not run for me: it crashes directly on launch.

Also, could you trigger the filtering on the select event of a checkbox and remove the button? Thanks.

**Comment by nguyenLisa** [comment]
Also, the develop branch was just updated. Please pull and resolve the conflicts.

**Comment by nguyenLisa** [comment]
Hi @gsvarma , I can still see the button in the code. This should not be in the code at all. Once a checkbox is selected/unselected, the filter action should happen right away. No need to press on any additional button.

**Comment by ghost** [comment]
**Output**: [ Updated ] 

filter_checkbox

**Review by nguyenLisa — APPROVED** [review]
LGTM

**Pull request merged**
