### PR TITLE
Library: Image

### PR DESCRIPTION
**Pull request by ghost**
This **PR** address **Issue** #6.

**Output**:

The following screenshot is the output shown after executing the code.

image

### CODE REVIEW

**Comment by ghost** [comment]
**Output**: [ + merge ] 

image _ output

**Review by nguyenLisa — CHANGES_REQUESTED** [review]
I cannot build the code (see screenshot). Please fix.

Capture d’écran 2019-04-20 à 14 46 30

**Comment by ghost** [comment]
Re-compiled the code and executed. It works. Please build the _GpaLib_ before executing _Prototype1_.

**Comment by nguyenLisa** [comment]
I'm still having the same error.

**Comment by ghost** [comment]
I have deleted local branches. Next, pulled the code from the [remote branch](https://github.com/gapran/sim_platform/tree/gpa-i6-image). And it still works in my system. @nguyenLisa 

Are you able to build the code? @osamic @HaseebAhmad23

**Review by nguyenLisa — APPROVED** [review]
LGTM.

I have modified the .pro file of GpaLib so that it works with MacOS. Please make sure that this doesn't break on your distribution @gsvarma. If it works fine, feel free to merge the PR.

**Comment by ghost** [comment]
I have tested the latest modification of **GpaLib.pro** file  on my distribution and it works fine. I cannot merge **PR** as it says "_You’re not authorized to merge this pull request._ ". @nguyenLisa

**Pull request merged**
