### PR TITLE
Layouts implementation

### PR DESCRIPTION
**Pull request by ghost**
This **PR** address issue #3.

It implements the following functionalities;
```
explicit Layout(QWidget *parent = 0);
void setMobile();
void setWeb();
void setIDE();
void setCLI();
```
### Output:

**Mobile**
mobile_output

**Web**
web_output

**IDE**
ide_output

**CLI**
cli_output

**Note**: The _Independent application_ layout looks similar to _IDE_. So, the user might use the _IDE_ layout functionality for _Independent application_ as well.

### CODE REVIEW

**Comment by ghost** [comment]
To have different **sizes** of layouts, change the following values.

https://github.com/gapran/sim_platform/blob/82a1c3fe21894ed832306595472ab48185938564/Prototype01/main.cpp#L20
https://github.com/gapran/sim_platform/blob/82a1c3fe21894ed832306595472ab48185938564/Prototype01/main.cpp#L21

**Comment by nguyenLisa** [comment]
Please fix merging conflicts

**Comment by ghost** [comment]
**Output**: [ +Merge ]

layout_output

**Comment by nguyenLisa** [comment]
I have three concerns:
- The layouts seem to be images in the background. This causes them to look stretched. Can this be fixed (by not using images for example)?
- The resize does not seem to work: when the application window is resized, the figure is stretched the same.
- The inner components go out of the layout. Is that normal?

Capture d’écran 2019-04-30 à 15 17 13

**Comment by gsvarma** [comment]
Here are my thoughts for the concerns mentioned.

1. Yes! the layouts are images on top of which the GUI elements are added. The coordinates and dimensions are to be taken care before rendering then we can get the desired output.
https://github.com/gapran/sim_platform/blob/bb6b78688526039c47392719fa6d520dfd6ad78d/SimPlatform/Prototype1/main.cpp#L34

2. Resize functionality is been looked into as part of issue #30.

3.  Coordinates needs to be given carefully.

**Comment by ghost** [comment]
Here are my thoughts for the concerns mentioned.

1. Yes! the layouts are images on top of which the GUI elements are added. The coordinates and dimensions are to be taken care before rendering then we can get the desired output.
https://github.com/gapran/sim_platform/blob/bb6b78688526039c47392719fa6d520dfd6ad78d/SimPlatform/Prototype1/main.cpp#L34

2. Resize functionality is being looked into as part of issue #30.

3.  Coordinates need to be given carefully.

**Comment by nguyenLisa** [comment]
I see. Then, please:
2. Include the resize in this PR.
1. and 3. I don't really like this system. Could you make it so the container in which we add the inner components is the inside of the layout? For example, when I want to add the table at coordinates (0,0), they show at the top left inside of the layout, and not outside.

**Comment by gsvarma** [comment]
Including resize would block this PR for some time until a possible solution is figured out. ( Reference - [UI with Qt Designer Wiki ](https://github.com/gapran/sim_platform/wiki/UI-with-Qt-Designer))

Yes! we can increment the co-ordinate values in library files with coordinates provided by user. But then, it is to be taken care while giving coordinate values. Shall we keep as it is or try as mentioned earlier by incrementing? Anyhow, the redering checks has to happen until all GUI elements falls into right place as they are embeded into layouts ( like inner child widgets ).

**Comment by gsvarma** [comment]
Including resize would block this PR for some time until a possible solution is figured out. ( Reference - [UI with Qt Designer](https://github.com/gapran/sim_platform/wiki/UI-with-Qt-Designer) Wiki )

Yes! we can increment the coordinate values in library files with coordinates provided by a user. But then, it is to be taken care while giving coordinate values. Shall we keep as it is or tries as mentioned earlier by incrementing? Anyhow, the rendering checks have to happen until all GUI elements fall into the right place as they are embedded into layouts ( like inner child widgets ).

**Comment by ghost** [comment]
Including resize would block this PR for some time until a possible solution is figured out. ( Reference - [UI with Qt Designer](https://github.com/gapran/sim_platform/wiki/UI-with-Qt-Designer) Wiki )

Yes! we can increment the coordinate values in library files with coordinates provided by a user. But then, it is to be taken care while giving coordinate values. Shall we keep as it is or tries as mentioned earlier by incrementing? Anyhow, the rendering checks have to happen until all GUI elements fall into the right place as they are not embedded into layouts ( like inner child widgets ).

**Comment by nguyenLisa** [comment]
From the wiki page, it seems like that if we know the elements in advance, the resize works. We do know them, right? Could you clarify what the issue is?

Why handle coordinates? Can we not set up a layout with a large frame and put the components inside?

**Comment by ghost** [comment]
Resize of GUI elements in a window works as shown below.

**Output**: [ fd26fc89df0e915036738a6cf92525be04f50230 ]

resizable

**Comment by ghost** [comment]
The layouts mentioned in issue #3 are added as background image for a window.

**Output**: [ 1224a96ea61e40aa3d38d9c70c821e0e43aab56e ]

resizable_layout

**Comment by ghost** [comment]
Now, adding GUI elements as layout on top of background image ( combining results of previous two commits ) results as following. 

**Output**: [ 5bcf82ec856bd7f7161f3c373e957f117f176518 ]

merge

Any thoughts on fixing this? @nguyenLisa @osamic @HaseebAhmad23 @rashmigupta1709

**Comment by ghost** [comment]
As discussed, the code base is updated to get desired output as shown in following screenshot.

layout_output

P.S. The co-ordinates need to be taken care of while changing layout or adding GUI elements.

**Review by nguyenLisa — APPROVED** [review]
LGTM

**Pull request merged**
