### PR TITLE
Table implemenatation

### PR DESCRIPTION
**Pull request by ghost**
This **PR** addresses **Issue** #4. It implements following functionalities;

```
    void createTable(int row, int column);
    void updateTable(int rowNo, int columnNo, QString value);
    void addTableHeaders(QStringList tableHeadersList);
    void addTableNameColumns(QStringList tableNameColumn);
    void addTableStatusColumns(QStringList tableStatusColumn);
    void addTableStartDateColumns(QStringList tableStartDateColumn);
    void addTableLastUpdateColumns(QStringList tableLastUpdateColumn);
    void addTableDescriptionColumns(QStringList tableDescriptionColumn);
    void addTableActionColumns(QStringList tableActionColumn);
    void findColumn(QString columnName);
    void sort(bool value);
    void applyFilter(QString columnFilterName, QString filterName);
    void applyBackgroundColor(QString backgroundColor);
    void applyBorderWidthColor(QStringList borderWidthColor);
    void show();
```

The existing **tested code** results in following **output**.

gpa-i4-table implementation

### CODE REVIEW

**Comment by ghost** [comment]
### **Travis CI** Update:

It is tested in Virtual Machine with similar settings / tools as in Travis Config and it works.

### **Reference**:

#### **Before Make** 

SimPlatform

Prototype01


#### **After Make** 

make_execution

SimPlatform_make

Prototype01_make

 **Note**: 

I am unable to rectify the Travis CI build. 

travis_build_error


Any thoughts? 
@osamic @HaseebAhmad23  @rashmigupta1709

**Comment by ghost** [comment]
**Update**:

There is no Library file ( _libSimPlatform.a_ ) in Travis build. :exclamation:
In similar setting of VM shows the file. :confused:

travis

**Comment by ghost** [comment]
**Travis CI Update**:

The missing **.a** file is uploaded manually but it did not fix the build as the path embedded is reflecting the file system where the library is created.

travis

**Comment by ghost** [comment]
There is no library file found with the name "**libSimPlatform.a**" apart from the one manually uploaded before.

find

**Comment by ghost** [comment]
**Output**: [ + Subdirs Template ]

table _ output

**Review by nguyenLisa — APPROVED** [review]
LGTM

**Pull request merged**
